server:
  port: 9000

application:
  kafka:
    topic: "demo-topic"

spring:
  application:
    name: demo-kafka
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
      client-id: "demo-producer"
    consumer:
      group-id: demo-group
      bootstrap-servers: "localhost:9092"
      client-id: "demo-consumer"

management:
  endpoints:
    web:
      exposure:
        include: "*"
